Comment out workflow configuration
Comment out the entire workflow configuration in cron_sanitizer.yml.

diff --git a/.github/workflows/cron_sanitizer.yml b/.github/workflows/cron_sanitizer.yml
--- a/.github/workflows/cron_sanitizer.yml
+++ b/.github/workflows/cron_sanitizer.yml
@@ -1,96 +1,96 @@
-name: Sanitizer
+# name: Sanitizer
 
-on:
-  schedule:
-    - cron: "0 6 * * SAT"
-  workflow_dispatch:
+# on:
+#   schedule:
+#     - cron: "0 6 * * SAT"
+#   workflow_dispatch:
 
-concurrency:
-  group: sanitizer-actions
-  cancel-in-progress: true
+# concurrency:
+#   group: sanitizer-actions
+#   cancel-in-progress: true
 
-env:
-  TZ: Europe/Berlin
-  TSAN_OPTIONS: ignore_noninstrumented_modules=1
-  UBSAN_OPTIONS: print_stacktrace=1
+# env:
+#   TZ: Europe/Berlin
+#   TSAN_OPTIONS: ignore_noninstrumented_modules=1
+#   UBSAN_OPTIONS: print_stacktrace=1
 
-defaults:
-  run:
-    shell: bash -Eeuxo pipefail {0}
+# defaults:
+#   run:
+#     shell: bash -Eeuxo pipefail {0}
 
-jobs:
-  build:
-    name: ${{ matrix.name }} ${{ matrix.build_type }} ${{ matrix.os }}
-    runs-on: ${{ matrix.os }}
-    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
-    env:
-      ASAN_OPTIONS: strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:detect_leaks=${{ contains(matrix.os, 'macos') && '0' || '1' }}
-    strategy:
-      fail-fast: false
-      matrix:
-        name: [ASan, TSan, UBSan]
-        os: [ubuntu-latest, macos-latest]
-        build_type: [Release, RelWithDebInfo, Debug]
-        exclude:
-          - name: "TSan"
-            os: macos-latest
-        include:
-          - name: "ASan"
-            os: ubuntu-latest
-            cxx_flags: "-fno-omit-frame-pointer -fsanitize=address -Wno-maybe-uninitialized"
+# jobs:
+#   build:
+#     name: ${{ matrix.name }} ${{ matrix.build_type }} ${{ matrix.os }}
+#     runs-on: ${{ matrix.os }}
+#     if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
+#     env:
+#       ASAN_OPTIONS: strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:detect_leaks=${{ contains(matrix.os, 'macos') && '0' || '1' }}
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         name: [ASan, TSan, UBSan]
+#         os: [ubuntu-latest, macos-latest]
+#         build_type: [Release, RelWithDebInfo, Debug]
+#         exclude:
+#           - name: "TSan"
+#             os: macos-latest
+#         include:
+#           - name: "ASan"
+#             os: ubuntu-latest
+#             cxx_flags: "-fno-omit-frame-pointer -fsanitize=address -Wno-maybe-uninitialized"
 
-          - name: "ASan"
-            os: macos-latest
-            cxx_flags: "-fno-omit-frame-pointer -fsanitize=address"
+#           - name: "ASan"
+#             os: macos-latest
+#             cxx_flags: "-fno-omit-frame-pointer -fsanitize=address"
 
-          - name: "TSan"
-            cxx_flags: "-fno-omit-frame-pointer -fsanitize=thread"
+#           - name: "TSan"
+#             cxx_flags: "-fno-omit-frame-pointer -fsanitize=thread"
 
-          - name: "UBSan"
-            os: ubuntu-latest
-            cxx_flags: "-fno-omit-frame-pointer -fsanitize=undefined,float-divide-by-zero -Wno-stringop-overflow"
+#           - name: "UBSan"
+#             os: ubuntu-latest
+#             cxx_flags: "-fno-omit-frame-pointer -fsanitize=undefined,float-divide-by-zero -Wno-stringop-overflow"
 
-          - name: "UBSan"
-            os: macos-latest
-            cxx_flags: "-fno-omit-frame-pointer -fsanitize=undefined,float-divide-by-zero,local-bounds,nullability -fno-sanitize=function -Wno-pass-failed"
+#           - name: "UBSan"
+#             os: macos-latest
+#             cxx_flags: "-fno-omit-frame-pointer -fsanitize=undefined,float-divide-by-zero,local-bounds,nullability -fno-sanitize=function -Wno-pass-failed"
 
-          - os: macos-latest
-            compiler: clang-latest
+#           - os: macos-latest
+#             compiler: clang-latest
 
-          - os: ubuntu-latest
-            compiler: gcc-latest
-            image: ghcr.io/seqan/gcc-latest
+#           - os: ubuntu-latest
+#             compiler: gcc-latest
+#             image: ghcr.io/seqan/gcc-latest
 
-          - name: "TSan"
-            os: ubuntu-latest
-            compiler: clang-latest
-            image: ghcr.io/seqan/clang-latest
-    container:
-      image: ${{ matrix.image || '' }}
-      volumes:
-        - /home/runner:/home/runner
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v7
+#           - name: "TSan"
+#             os: ubuntu-latest
+#             compiler: clang-latest
+#             image: ghcr.io/seqan/clang-latest
+#     container:
+#       image: ${{ matrix.image || '' }}
+#       volumes:
+#         - /home/runner:/home/runner
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v7
 
-      - name: Setup compiler
-        if: contains(matrix.os, 'macos')
-        uses: seqan/actions/setup-compiler@main
-        with:
-          compiler: ${{ matrix.compiler }}
+#       - name: Setup compiler
+#         if: contains(matrix.os, 'macos')
+#         uses: seqan/actions/setup-compiler@main
+#         with:
+#           compiler: ${{ matrix.compiler }}
 
-      - name: Configure tests
-        run: |
-          mkdir build && cd build
-          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
-                   -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}"
-          make gtest_main
+#       - name: Configure tests
+#         run: |
+#           mkdir build && cd build
+#           cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
+#                    -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}"
+#           make gtest_main
 
-      - name: Build tests
-        working-directory: build
-        run: make -k api_test cli_test display_layout measure_hyperloglog
+#       - name: Build tests
+#         working-directory: build
+#         run: make -k api_test cli_test display_layout measure_hyperloglog
 
-      - name: Run tests
-        working-directory: build
-        run: ctest . -j --output-on-failure
+#       - name: Run tests
+#         working-directory: build
+#         run: ctest . -j --output-on-failure
 
